version: '3.7'

services:
  tron:
    build: ./bot
    image: tron
    depends_on:
      - postgresql
    volumes:
      - /srv/docker/tron/logs:/home/bot/Tron/logs

  postgresql:
    restart: always
    image: sameersbn/postgresql:10-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=
      - DB_PASS=
      - DB_NAME=tron
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
